import React, { forwardRef } from 'react';
import { BookOpen } from 'lucide-react';

const PdfTemplate = forwardRef(({ title, overall, topics, quality }, ref) => {
  return (
    <div 
      ref={ref} 
      style={{
        width: '800px', // A4 width proportion
        padding: '40px',
        background: '#ffffff',
        color: '#1a1a1a',
        fontFamily: 'Helvetica, Arial, sans-serif',
        position: 'absolute',
        top: '-9999px', // Hide from screen but keep in DOM
        left: '-9999px',
        zIndex: -1
      }}
    >
      {/* Header */}
      <div style={{ display: 'flex', alignItems: 'center', borderBottom: '2px solid #4f46e5', paddingBottom: '20px', marginBottom: '30px' }}>
        <div style={{ background: '#4f46e5', padding: '12px', borderRadius: '12px', marginRight: '20px' }}>
          <BookOpen size={32} color="#ffffff" />
        </div>
        <div>
          <h1 style={{ margin: 0, color: '#4f46e5', fontSize: '28px', fontWeight: 800 }}>Alexandria</h1>
          <h2 style={{ margin: '5px 0 0 0', color: '#4b5563', fontSize: '18px', fontWeight: 500 }}>{title || 'Lecture Study Guide'}</h2>
        </div>
      </div>

      {/* Overview */}
      <div style={{ marginBottom: '30px' }}>
        <h3 style={{ color: '#4f46e5', fontSize: '20px', borderBottom: '1px solid #e5e7eb', paddingBottom: '8px', marginBottom: '15px' }}>Overview</h3>
        <p style={{ lineHeight: 1.6, fontSize: '15px', color: '#374151', margin: 0 }}>
          {overall || 'No overview available for this session.'}
        </p>
      </div>

      {/* Key Concepts */}
      <div style={{ marginBottom: '30px' }}>
        <h3 style={{ color: '#4f46e5', fontSize: '20px', borderBottom: '1px solid #e5e7eb', paddingBottom: '8px', marginBottom: '15px' }}>Key Concepts & Learning Outcomes</h3>
        {topics && topics.length > 0 ? (
          <ul style={{ paddingLeft: '20px', margin: 0 }}>
            {topics.map((t, i) => (
              <li key={i} style={{ marginBottom: '15px', lineHeight: 1.6, fontSize: '15px', color: '#374151' }}>
                <strong style={{ color: '#111827' }}>{t.topic}:</strong> {t.summary}
              </li>
            ))}
          </ul>
        ) : (
          <p style={{ color: '#6b7280', fontStyle: 'italic', fontSize: '14px' }}>Topics are being generated.</p>
        )}
      </div>

      {/* Glossary Placeholder - If we had a specific glossary field, we'd map it here. For now, it's structurally present. */}
      <div style={{ marginBottom: '40px' }}>
        <h3 style={{ color: '#4f46e5', fontSize: '20px', borderBottom: '1px solid #e5e7eb', paddingBottom: '8px', marginBottom: '15px' }}>Important Terms & Notes</h3>
        <div style={{ background: '#f9fafb', padding: '20px', borderRadius: '8px', border: '1px solid #e5e7eb' }}>
          <ul style={{ paddingLeft: '20px', margin: 0, color: '#374151', lineHeight: 1.6, fontSize: '15px' }}>
            <li><strong>Review:</strong> Make sure to revisit the concepts around {topics && topics[0] ? topics[0].topic : 'the core topics'} as they are fundamental.</li>
            <li><strong>Quality Check:</strong> {quality?.warnings?.length > 0 ? 'Note that this summary had some generation warnings.' : 'This transcript generated a clean, high-quality summary.'}</li>
          </ul>
        </div>
      </div>

      {/* Footer (Not visually placed at absolute bottom here because html2canvas just snaps the div. We add the real footer per-page via jsPDF). This is just a fallback end note. */}
      <div style={{ textAlign: 'center', marginTop: '40px', paddingTop: '20px', borderTop: '1px solid #e5e7eb', color: '#9ca3af', fontSize: '12px' }}>
        Generated by Alexandria · alexandria-ai.onrender.com
      </div>
    </div>
  );
});

export default PdfTemplate;
